/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.thecorralcoffee.sistemahuellitas.vista;

import com.thecorralcoffee.sistemahuellitas.controlador.MovimientoController;
import com.thecorralcoffee.sistemahuellitas.controlador.ProductoController;
import com.thecorralcoffee.sistemahuellitas.model.Movimientos;
import com.thecorralcoffee.sistemahuellitas.model.Producto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oliva
 */
public class FrmMovimiento extends javax.swing.JFrame {
    private final MovimientoController movimientoController;
    private final ProductoController productoController;
    private int movimientoEditandoId = -1;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMovimiento.class.getName());

    /**
     * Creates new form FrmMovimiento
     */
    public FrmMovimiento() {
        initComponents();
        movimientoController = new MovimientoController();
        productoController = new ProductoController();
        cargarProductos();
        cargarTipos();
        cargarMovimientos();
        limpiarCampos();
        setLocationRelativeTo(null);
    }
    
    private void cargarProductos() {
    cbmProducto.removeAllItems();
    List<Producto> productos = productoController.listarProductos();
    for (Producto p : productos) {
        cbmProducto.addItem(p.getId() + " - " + p.getNombre());
    }
    }
    
    private void cargarTipos() {
    cbmTipo.removeAllItems();
    cbmTipo.addItem("ENTRADA");
    cbmTipo.addItem("SALIDA");
    }  
    private void cargarMovimientos() {
    List<Movimientos> movimientos = movimientoController.listarMovimientos();
    DefaultTableModel modelo = (DefaultTableModel) tblMovimientos.getModel();
    modelo.setRowCount(0);
    for (Movimientos m : movimientos) {
        Producto producto = productoController.buscarProducto(m.getProductoId());
        String nombreProducto = "";
        if (producto != null) {
            nombreProducto = producto.getNombre();
        }
        modelo.addRow(new Object[]{
            m.getId(),
            nombreProducto,
            m.getTipo(),
            m.getCantidad(),
            m.getFecha()
        });
    }
    }    
    private void limpiarCampos() {
    txtCantidad.setText("");
    if (cbmProducto.getItemCount() > 0) {
        cbmProducto.setSelectedIndex(0);
    }
    if (cbmTipo.getItemCount() > 0) {
        cbmTipo.setSelectedIndex(0);
    }
    txtCantidad.requestFocus();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbProducto = new javax.swing.JLabel();
        lbTipo = new javax.swing.JLabel();
        lbCantidad = new javax.swing.JLabel();
        cbmProducto = new javax.swing.JComboBox<>();
        cbmTipo = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();
        btnRegistroMovi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMovimientos = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnIrInventario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo.setText("MOVIMIENTOS DE INVENTARIO HUELLITAS");

        lbProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbProducto.setForeground(new java.awt.Color(255, 255, 255));
        lbProducto.setText("PRODUCTO:");

        lbTipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTipo.setForeground(new java.awt.Color(255, 255, 255));
        lbTipo.setText("TIPO:");

        lbCantidad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbCantidad.setForeground(new java.awt.Color(255, 255, 255));
        lbCantidad.setText("CANTIDAD:");

        cbmProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbmTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRegistroMovi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistroMovi.setText("Registrar Movimiento");
        btnRegistroMovi.addActionListener(this::btnRegistroMoviActionPerformed);

        tblMovimientos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "PRODUCTO", "TIPO", "CANTIDAD", "FECHA"
            }
        ));
        jScrollPane1.setViewportView(tblMovimientos);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnIrInventario.setText("Ver Inventario");
        btnIrInventario.addActionListener(this::btnIrInventarioActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnIrInventario)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(213, 213, 213)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbTipo)
                                .addComponent(lbCantidad)
                                .addComponent(lbProducto))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnRegistroMovi)
                                    .addComponent(cbmProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cbmTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(97, 97, 97)
                            .addComponent(lbTitulo))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(264, 264, 264)
                            .addComponent(btnEditar)
                            .addGap(109, 109, 109)
                            .addComponent(btnEliminar))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbProducto)
                    .addComponent(cbmProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipo)
                    .addComponent(cbmTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistroMovi)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnIrInventario)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int fila = tblMovimientos.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this,"Selecciona un movimiento.");
        return;
    }
    int id = (int) tblMovimientos.getValueAt(fila, 0);
    Movimientos movimiento = movimientoController.buscarPorId(id);
    if (movimiento == null) {
        JOptionPane.showMessageDialog(this,"No se encontró el movimiento.");
        return;
    }
    movimientoEditandoId = movimiento.getId();

    //seleccionar producto
    for (int i = 0; i < cbmProducto.getItemCount(); i++) {
        String item = cbmProducto.getItemAt(i);
        int productoId = Integer.parseInt(item.split(" - ")[0]);
        if (productoId == movimiento.getProductoId()) {
            cbmProducto.setSelectedIndex(i);
            break;
        }
    }
    //seleccionar tipo
    cbmTipo.setSelectedItem(movimiento.getTipo());
    //cantidad
    txtCantidad.setText(String.valueOf(movimiento.getCantidad()));
    //cambiar botón
    btnRegistroMovi.setText("Actualizar Movimiento");
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tblMovimientos.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this,
                "Selecciona un movimiento.");
        return;
    }
    
    int id = (int) tblMovimientos.getValueAt(fila, 0);

    int confirmar = JOptionPane.showConfirmDialog(
            this,"¿Deseas eliminar este movimiento?","Confirmar eliminación",
            JOptionPane.YES_NO_OPTION
    );

    if (confirmar == JOptionPane.YES_OPTION) {
        if (movimientoController.eliminarMovimiento(id)) {
            JOptionPane.showMessageDialog(this,"Movimiento eliminado correctamente.");

            cargarMovimientos();

        } else {

            JOptionPane.showMessageDialog(this,
                    "No se pudo eliminar el movimiento.");
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistroMoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroMoviActionPerformed
        if (cbmProducto.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Selecciona un producto.");
        return;
    }

    if (txtCantidad.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingresa una cantidad.");
        txtCantidad.requestFocus();
        return;
    }

    int cantidad;

    try {
        cantidad = Integer.parseInt(txtCantidad.getText().trim());

        if (cantidad <= 0) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor que 0.");
            return;
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "La cantidad debe ser un número entero.");
        txtCantidad.requestFocus();
        return;
    }

    //obtener ID del producto
    String productoSeleccionado = cbmProducto.getSelectedItem().toString();
    int productoId = Integer.parseInt(productoSeleccionado.split(" - ")[0]);

    String tipo = cbmTipo.getSelectedItem().toString();

    if (movimientoEditandoId == -1) {

        Movimientos movimiento = new Movimientos();
        movimiento.setTipo(tipo);
        movimiento.setCantidad(cantidad);
        movimiento.setProductoId(productoId);

        if (movimientoController.insertarMovimiento(movimiento)) {

            JOptionPane.showMessageDialog(this,
                    "Movimiento registrado correctamente.");
            cargarMovimientos();
            limpiarCampos();

        } else {
            JOptionPane.showMessageDialog(this,"No se pudo registrar el movimiento.");
        }

    } else {

        Movimientos movimiento = movimientoController.buscarPorId(movimientoEditandoId);

        if (movimiento != null) {

            movimiento.setTipo(tipo);
            movimiento.setCantidad(cantidad);
            movimiento.setProductoId(productoId);

            if (movimientoController.actualizarMovimiento(movimiento)) {

                JOptionPane.showMessageDialog(this,"Movimiento actualizado correctamente.");
                cargarMovimientos();
                limpiarCampos();
                movimientoEditandoId = -1;
                btnRegistroMovi.setText("Registrar Movimiento");

            } else {

                JOptionPane.showMessageDialog(this,"No se pudo actualizar el movimiento.");
            }
        }
    }
    }//GEN-LAST:event_btnRegistroMoviActionPerformed

    private void btnIrInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrInventarioActionPerformed
        FrmInventario frm = new FrmInventario();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnIrInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMovimiento().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIrInventario;
    private javax.swing.JButton btnRegistroMovi;
    private javax.swing.JComboBox<String> cbmProducto;
    private javax.swing.JComboBox<String> cbmTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCantidad;
    private javax.swing.JLabel lbProducto;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTable tblMovimientos;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
