/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.thecorralcoffee.sistemahuellitas.vista;
import com.thecorralcoffee.sistemahuellitas.controlador.ClienteController;
import com.thecorralcoffee.sistemahuellitas.controlador.MascotaController;
import com.thecorralcoffee.sistemahuellitas.model.Cliente;
import com.thecorralcoffee.sistemahuellitas.model.Mascota;
import java.time.LocalDate;
import javax.swing.JOptionPane;
/**
 *
 * @author oliva
 */
public class FrmNuevaMascota extends javax.swing.JFrame {
    private final MascotaController mascotaController;
    private final ClienteController clienteController;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmNuevaMascota.class.getName());

    /**
     * Creates new form FrmNuevaMascota
     */
    public FrmNuevaMascota() {
        initComponents();
        mascotaController = new MascotaController();
        clienteController = new ClienteController();
        cargarClientes();
        setLocationRelativeTo(null);
    }
    
    private void cargarClientes() {
    cbmPropietario.removeAllItems();
    for (Cliente c : clienteController.listarClientes()) {
        cbmPropietario.addItem(c.getId() + " - " + c.getNombre());
    }
    }
    
    private void limpiarCampos() {
    txtNombre.setText("");
    txtEspecie.setText("");
    txtRaza.setText("");
    txtNacimiento.setText("");
    if (cbmPropietario.getItemCount() > 0) {
        cbmPropietario.setSelectedIndex(0);
    }
    txtNombre.requestFocus();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbRaza = new javax.swing.JLabel();
        lbEspecie = new javax.swing.JLabel();
        lbNacimiento = new javax.swing.JLabel();
        lbPropietario = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtRaza = new javax.swing.JTextField();
        txtEspecie = new javax.swing.JTextField();
        txtNacimiento = new javax.swing.JTextField();
        cbmPropietario = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo.setText("NUEVA MASCOTA");

        lbNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(255, 255, 255));
        lbNombre.setText("NOMBRE:");

        lbRaza.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbRaza.setForeground(new java.awt.Color(255, 255, 255));
        lbRaza.setText("RAZA:");

        lbEspecie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbEspecie.setForeground(new java.awt.Color(255, 255, 255));
        lbEspecie.setText("ESPECIE:");

        lbNacimiento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNacimiento.setForeground(new java.awt.Color(255, 255, 255));
        lbNacimiento.setText("NACIMIENTO:");

        lbPropietario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbPropietario.setForeground(new java.awt.Color(255, 255, 255));
        lbPropietario.setText("DUEÑO:");

        cbmPropietario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTitulo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbNombre)
                            .addComponent(lbNacimiento)
                            .addComponent(lbPropietario)
                            .addComponent(lbRaza)
                            .addComponent(lbEspecie))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(33, 33, 33)
                                .addComponent(btnVolver))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombre)
                                .addComponent(txtRaza)
                                .addComponent(txtEspecie)
                                .addComponent(txtNacimiento)
                                .addComponent(cbmPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(267, 267, 267))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEspecie)
                    .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRaza)
                    .addComponent(txtRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNacimiento)
                    .addComponent(txtNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPropietario)
                    .addComponent(cbmPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnVolver))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        FrmMascotas frm = new FrmMascotas();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    String nombre = txtNombre.getText().trim();
    String especie = txtEspecie.getText().trim();
    String raza = txtRaza.getText().trim();
    String fechaTexto = txtNacimiento.getText().trim();

    if (nombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingresa el nombre de la mascota.");
        txtNombre.requestFocus();
        return;
    }

    if (nombre.length() < 2 || nombre.length() > 50) {
        JOptionPane.showMessageDialog(this, "El nombre debe tener entre 2 y 50 caracteres.");
        txtNombre.requestFocus();
        return;
    }

    if (!nombre.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ0-9 ]+")) {
        JOptionPane.showMessageDialog(this, "El nombre contiene caracteres no válidos.");
        txtNombre.requestFocus();
        return;
    }

    if (especie.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingresa la especie.");
        txtEspecie.requestFocus();
        return;
    }

    if (especie.length() < 3 || especie.length() > 30) {
        JOptionPane.showMessageDialog(this, "La especie debe tener entre 3 y 30 caracteres.");
        txtEspecie.requestFocus();
        return;
    }

    if (!especie.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ ]+")) {
        JOptionPane.showMessageDialog(this, "La especie solo puede contener letras.");
        txtEspecie.requestFocus();
        return;
    }

    if (raza.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingresa la raza.");
        txtRaza.requestFocus();
        return;
    }

    if (raza.length() < 2 || raza.length() > 50) {
        JOptionPane.showMessageDialog(this, "La raza debe tener entre 2 y 50 caracteres.");
        txtRaza.requestFocus();
        return;
    }

    if (!raza.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ0-9 -]+")) {
        JOptionPane.showMessageDialog(this, "La raza contiene caracteres no válidos.");
        txtRaza.requestFocus();
        return;
    }

    if (fechaTexto.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingresa la fecha de nacimiento.");
        txtNacimiento.requestFocus();
        return;
    }

    if (!fechaTexto.matches("\\d{4}-\\d{2}-\\d{2}")) {
        JOptionPane.showMessageDialog(this, "La fecha debe tener el formato AAAA-MM-DD.");
        txtNacimiento.requestFocus();
        return;
    }

    LocalDate fechaNac;

    try {
        fechaNac = LocalDate.parse(fechaTexto);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "La fecha ingresada no es válida.");
        txtNacimiento.requestFocus();
        return;
    }

    if (fechaNac.isAfter(LocalDate.now())) {
        JOptionPane.showMessageDialog(this, "La fecha de nacimiento no puede ser futura.");
        txtNacimiento.requestFocus();
        return;
    }

    if (cbmPropietario.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Selecciona el dueño de la mascota.");
        cbmPropietario.requestFocus();
        return;
    }

    String propietario = cbmPropietario.getSelectedItem().toString();

    if (propietario.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Selecciona un dueño válido.");
        cbmPropietario.requestFocus();
        return;
    }

    try {
        int clienteId = Integer.parseInt(propietario.split(" - ")[0]);

        Mascota mascota = new Mascota(
                nombre,
                especie,
                raza,
                fechaNac,
                clienteId
        );

        if (mascotaController.insertarMascota(mascota)) {
            JOptionPane.showMessageDialog(this, "Mascota registrada correctamente.");
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar la mascota.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El dueño seleccionado no es válido.");
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmNuevaMascota().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbmPropietario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbEspecie;
    private javax.swing.JLabel lbNacimiento;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPropietario;
    private javax.swing.JLabel lbRaza;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextField txtNacimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRaza;
    // End of variables declaration//GEN-END:variables
}
